import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import * as Sentry from "npm:@sentry/deno";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Sentry.init({
  dsn: "https://ce035a76b6157a602d88c53eab6570e4@o4509804047958016.ingest.us.sentry.io/4510552540971008",
  environment: Deno.env.get("SUPABASE_URL")?.includes("staging") ? "staging" : "production",
  tracesSampleRate: 0.1,
});

interface ClockActionRequest {
  employee_id: string;
  phone: string;
  action: "clock_in" | "clock_out" | "break_start" | "break_end";
  /**
   * Unique ID generated by the mobile app for this specific action.
   * Sending the same client_action_id twice is a no-op — the server
   * returns the already-processed time_entry without creating a duplicate.
   * Format: any non-empty string (UUID recommended).
   */
  client_action_id?: string;
  /**
   * ISO-8601 timestamp of the event as measured on the employee device.
   * Use when replaying offline actions. If omitted, server time is used.
   * Example: "2026-06-30T14:32:00.000Z"
   */
  event_time?: string;
  /** Links the shift to a route_appointments row. */
  route_appointment_id?: string;
  /** Links the shift to a jobs row (preferred over route_appointment_id for new jobs). */
  job_id?: string;
  notes?: string;
  /** YYYY-MM-DD — employee's local calendar date. */
  local_date?: string;
  latitude?: number;
  longitude?: number;
}

// ── Haversine distance (metres) ───────────────────────────────────────────────
function haversineMetres(
  lat1: number, lon1: number,
  lat2: number, lon2: number,
): number {
  const R = 6371000; // Earth radius in metres
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/**
 * Records an action for idempotency. Must be AWAITED: `insert()` returns a lazy
 * thenable, not a Promise, so calling `.catch()` on it throws a TypeError — which
 * aborted the request *after* the time entry had already been written (the app saw
 * a 500 for an action that actually succeeded) and left the log row unwritten, so
 * replays were never deduplicated. Failures here stay non-fatal.
 */
async function writeActionLog(
  supabase: ReturnType<typeof createClient>,
  entry: {
    client_action_id: string;
    time_entry_id: string;
    employee_id: string;
    action: ClockActionRequest["action"];
    event_time: string;
  },
): Promise<void> {
  try {
    const { error } = await supabase.from("time_entry_action_log").insert(entry);
    if (error) console.error(`Failed to write action log (${entry.action}):`, error);
  } catch (e) {
    console.error(`Failed to write action log (${entry.action}):`, e);
  }
}

serve(async (req) => {
  return await Sentry.withScope(async (scope) => {
    Sentry.setTag("function", "employee-clock-action");

    try {
      if (req.method === "OPTIONS") {
        return new Response(null, { headers: corsHeaders });
      }

      const body: ClockActionRequest = await req.json();
      const {
        employee_id, phone, action,
        client_action_id,
        event_time,
        route_appointment_id,
        job_id,
        notes,
        local_date,
        latitude,
        longitude,
      } = body;

      Sentry.setTag("action", action);
      Sentry.addBreadcrumb({ message: `Clock action: ${action} for employee ${employee_id}`, level: "info" });
      console.log(`Clock action request: ${action} for employee ${employee_id}`, {
        client_action_id,
        has_event_time: !!event_time,
        job_id: job_id ?? null,
      });

      // ── Validate required fields ────────────────────────────────────────────
      if (!employee_id || !phone || !action) {
        return new Response(
          JSON.stringify({ error: "Missing required fields: employee_id, phone, and action are required" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      const supabase = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
      );

      // ── Idempotency check ───────────────────────────────────────────────────
      // Look up client_action_id in the action log (not in time_entries).
      // Each action type has its own log row, so clock_in and clock_out are
      // independently idempotent even though they share a time_entries row.
      if (client_action_id) {
        const { data: logEntry } = await supabase
          .from("time_entry_action_log")
          .select("time_entry_id")
          .eq("client_action_id", client_action_id)
          .maybeSingle();

        if (logEntry) {
          const { data: cachedEntry } = await supabase
            .from("time_entries")
            .select("*")
            .eq("id", logEntry.time_entry_id)
            .maybeSingle();

          console.log(`Duplicate client_action_id detected: ${client_action_id} — returning cached result`);
          return new Response(
            JSON.stringify({
              success: true,
              action,
              duplicate: true,
              employee: { id: employee_id },
              time_entry: cachedEntry,
            }),
            { headers: { ...corsHeaders, "Content-Type": "application/json" } },
          );
        }
      }

      // ── Authenticate employee ───────────────────────────────────────────────
      const { data: employee, error: employeeError } = await supabase
        .from("employees")
        .select("id, user_id, phone, first_name, last_name")
        .eq("id", employee_id)
        .eq("phone", phone)
        .maybeSingle();

      if (employeeError || !employee) {
        console.error("Employee not found or phone mismatch:", employeeError);
        return new Response(
          JSON.stringify({ error: "Employee not found or phone number does not match" }),
          { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      Sentry.setUser({ id: employee.id });

      // ── Server-side geofence validation (clock_in only) ─────────────────────
      // Only runs when a job_id is provided and that job has site coordinates.
      if (action === "clock_in" && job_id && latitude != null && longitude != null) {
        const { data: job } = await supabase
          .from("jobs")
          .select("site_latitude, site_longitude, geofence_radius_meters")
          .eq("id", job_id)
          .maybeSingle();

        if (job?.site_latitude != null && job?.site_longitude != null) {
          const radiusM = job.geofence_radius_meters ?? 200;
          const distanceM = haversineMetres(
            latitude, longitude,
            Number(job.site_latitude), Number(job.site_longitude),
          );

          if (distanceM > radiusM) {
            console.warn(`Geofence violation: employee ${employee_id} is ${Math.round(distanceM)}m from site (limit ${radiusM}m)`);
            return new Response(
              JSON.stringify({
                error: "You are too far from the job site to clock in",
                distance_metres: Math.round(distanceM),
                allowed_metres: radiusM,
              }),
              { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          console.log(`Geofence OK: employee ${employee_id} is ${Math.round(distanceM)}m from site`);
        }
      }

      // ── Resolve calendar date ───────────────────────────────────────────────
      // Use client's local date when provided; fall back to server UTC date.
      const today = local_date || new Date().toISOString().split("T")[0];

      // ── Resolve event timestamp ─────────────────────────────────────────────
      // Prefer the device-provided event_time (for offline replay accuracy);
      // fall back to server now().
      const now = event_time && !isNaN(Date.parse(event_time))
        ? new Date(event_time).toISOString()
        : new Date().toISOString();

      console.log(`Using date: ${today}, timestamp: ${now} (event_time provided: ${event_time ? "yes" : "no"})`);

      // ── Find existing time entry for today ─────────────────────────────────
      let existingEntry = null;

      const { data: activeEntry } = await supabase
        .from("time_entries")
        .select("*")
        .eq("employee_id", employee_id)
        .eq("date", today)
        .not("clock_in_time", "is", null)
        .is("clock_out_time", null)
        .order("clock_in_time", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (activeEntry) {
        existingEntry = activeEntry;
        console.log("Found active session:", { id: activeEntry.id, status: activeEntry.status });
      } else {
        const { data: scheduledEntry } = await supabase
          .from("time_entries")
          .select("*")
          .eq("employee_id", employee_id)
          .eq("date", today)
          .eq("status", "scheduled")
          .is("clock_in_time", null)
          .order("created_at", { ascending: true })
          .limit(1)
          .maybeSingle();

        if (scheduledEntry) {
          existingEntry = scheduledEntry;
          console.log("Found scheduled entry:", { id: scheduledEntry.id, status: scheduledEntry.status });
        }
      }

      let timeEntry;

      // ── Handle each action ─────────────────────────────────────────────────
      switch (action) {
        case "clock_in": {
          // Resolve appointment if not provided
          let appointmentId = route_appointment_id;
          if (!appointmentId && !job_id) {
            const { data: todaysAppt } = await supabase
              .from("route_appointments")
              .select("id")
              .eq("user_id", employee.user_id)
              .eq("scheduled_date", today)
              .contains("assigned_employees", [employee_id])
              .limit(1)
              .maybeSingle();

            if (todaysAppt) {
              appointmentId = todaysAppt.id;
              console.log(`Auto-linked appointment: ${appointmentId}`);
            }
          }

          const clockInFields = {
            clock_in_time: now,
            event_time: now,
            status: "in_progress",
            route_appointment_id: appointmentId ?? existingEntry?.route_appointment_id ?? null,
            job_id: job_id ?? existingEntry?.job_id ?? null,
            notes: notes ?? existingEntry?.notes ?? null,
            clock_in_latitude: latitude ?? existingEntry?.clock_in_latitude ?? null,
            clock_in_longitude: longitude ?? existingEntry?.clock_in_longitude ?? null,
          };

          if (existingEntry) {
            const { data, error } = await supabase
              .from("time_entries")
              .update(clockInFields)
              .eq("id", existingEntry.id)
              .select()
              .single();
            if (error) throw error;
            timeEntry = data;
          } else {
            const { data, error } = await supabase
              .from("time_entries")
              .insert({ employee_id, user_id: employee.user_id, date: today, ...clockInFields })
              .select()
              .single();
            if (error) throw error;
            timeEntry = data;
          }

          // Log action for idempotency (non-fatal if it fails)
          if (client_action_id) {
            await writeActionLog(supabase, {
              client_action_id,
              time_entry_id: timeEntry.id,
              employee_id,
              action: "clock_in",
              event_time: now,
            });
          }

          console.log(`Clock-in for employee ${employee_id}, entry ${timeEntry.id}`);
          supabase.functions.invoke("send-clock-notifications", {
            body: { timeEntryId: timeEntry.id, eventType: "clock_in" },
          }).catch((err) => console.error("Error sending clock-in notifications:", err));
          break;
        }

        case "clock_out": {
          if (!existingEntry) {
            return new Response(
              JSON.stringify({ error: "No active time entry found for today. Please clock in first." }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          if (existingEntry.status !== "in_progress" && existingEntry.status !== "on_break") {
            return new Response(
              JSON.stringify({ error: `Cannot clock out. Current status: ${existingEntry.status}` }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          const { data, error } = await supabase
            .from("time_entries")
            .update({
              clock_out_time: now,
              event_time: now,
              status: "completed",
              notes: notes ?? existingEntry.notes,
              clock_out_latitude: latitude ?? null,
              clock_out_longitude: longitude ?? null,
            })
            .eq("id", existingEntry.id)
            .select()
            .single();

          if (error) throw error;
          timeEntry = data;

          if (client_action_id) {
            await writeActionLog(supabase, {
              client_action_id,
              time_entry_id: timeEntry.id,
              employee_id,
              action: "clock_out",
              event_time: now,
            });
          }

          console.log(`Clock-out for employee ${employee_id}`);
          supabase.functions.invoke("send-clock-notifications", {
            body: { timeEntryId: timeEntry.id, eventType: "clock_out" },
          }).catch((err) => console.error("Error sending clock-out notifications:", err));
          break;
        }

        case "break_start": {
          if (!existingEntry) {
            return new Response(
              JSON.stringify({ error: "No active time entry found for today. Please clock in first." }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          if (existingEntry.status !== "in_progress") {
            return new Response(
              JSON.stringify({ error: `Cannot start break. Current status: ${existingEntry.status}` }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          const { data, error } = await supabase
            .from("time_entries")
            .update({
              break_start_time: now,
              break_end_time: null,
              status: "on_break",
              notes: notes ?? existingEntry.notes,
            })
            .eq("id", existingEntry.id)
            .select()
            .single();

          if (error) throw error;
          timeEntry = data;

          if (client_action_id) {
            await writeActionLog(supabase, {
              client_action_id,
              time_entry_id: timeEntry.id,
              employee_id,
              action: "break_start",
              event_time: now,
            });
          }

          console.log(`Break started for employee ${employee_id}`);
          break;
        }

        case "break_end": {
          if (!existingEntry) {
            return new Response(
              JSON.stringify({ error: "No active time entry found for today. Please clock in first." }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          if (existingEntry.status !== "on_break") {
            return new Response(
              JSON.stringify({ error: `Cannot end break. Current status: ${existingEntry.status}` }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }

          const { data, error } = await supabase
            .from("time_entries")
            .update({
              break_end_time: now,
              status: "in_progress",
              notes: notes ?? existingEntry.notes,
            })
            .eq("id", existingEntry.id)
            .select()
            .single();

          if (error) throw error;
          timeEntry = data;

          if (client_action_id) {
            await writeActionLog(supabase, {
              client_action_id,
              time_entry_id: timeEntry.id,
              employee_id,
              action: "break_end",
              event_time: now,
            });
          }

          console.log(`Break ended for employee ${employee_id}`);
          break;
        }

        default:
          return new Response(
            JSON.stringify({ error: "Invalid action. Must be one of: clock_in, clock_out, break_start, break_end" }),
            { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
          );
      }

      return new Response(
        JSON.stringify({
          success: true,
          action,
          duplicate: false,
          employee: { id: employee.id, name: `${employee.first_name} ${employee.last_name}` },
          time_entry: timeEntry,
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    } catch (error) {
      Sentry.captureException(error);
      console.error("Error in employee-clock-action:", error);
      const message = error instanceof Error ? error.message : "Unknown error occurred";
      return new Response(
        JSON.stringify({ error: message }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }
  });
});
