-- ─────────────────────────────────────────────────────────────────────────────
-- Fix 1: Replace the UTC-based missed-shift cron with one that calls the
--         existing timezone-aware refresh_job_temporal_statuses() function.
--
-- Fix 2: Move client_action_id out of time_entries (where it was overwritten
--         by every action on the same row) into a dedicated action-log table,
--         giving full idempotency for all four clock actions independently.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Fix 1: Cron — call existing timezone-aware function ───────────────────────
-- The previous cron used CURRENT_DATE (UTC) directly, which is the same bug
-- that was corrected in 20260611150000_fix_job_temporal_status_timezone.sql.
-- public.refresh_job_temporal_statuses() already handles per-owner timezones
-- and the 6-hour overdue threshold, so we just call it on a schedule.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    -- Remove the broken UTC cron added in the previous migration.
    BEGIN
      PERFORM cron.unschedule('auto-mark-missed-shifts');
    EXCEPTION WHEN others THEN NULL;
    END;

    -- Remove old cron if it was already registered under a different name.
    BEGIN
      PERFORM cron.unschedule('refresh-job-temporal-statuses');
    EXCEPTION WHEN others THEN NULL;
    END;

    -- Run every 30 minutes so job statuses stay fresh without UTC drift.
    PERFORM cron.schedule(
      'refresh-job-temporal-statuses',
      '*/30 * * * *',
      $cron$
        SELECT public.refresh_job_temporal_statuses();
      $cron$
    );
  END IF;
END;
$$;

-- ── Fix 2: Remove client_action_id from time_entries ─────────────────────────
-- Storing it on the shift row meant every new action in the same shift
-- overwrote the previous action's ID, leaving only the latest one protected.

ALTER TABLE public.time_entries
  DROP COLUMN IF EXISTS client_action_id;

-- ── Fix 2: Action-log table ───────────────────────────────────────────────────
-- One row per clock action. client_action_id lives here so all four actions
-- (clock_in, clock_out, break_start, break_end) are independently idempotent.
--
-- How idempotency works:
--   1. App generates a UUID before sending the request (saved locally).
--   2. Backend checks this table for that UUID before processing.
--   3. If found → return the original time_entry_id as a cached response.
--   4. If not found → perform the action, then insert a row here.

CREATE TABLE IF NOT EXISTS public.time_entry_action_log (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- The UUID generated by the mobile app to identify this specific action.
  client_action_id text        NOT NULL,
  time_entry_id    uuid        NOT NULL REFERENCES public.time_entries(id) ON DELETE CASCADE,
  employee_id      uuid        NOT NULL,
  action           text        NOT NULL CHECK (action IN ('clock_in', 'clock_out', 'break_start', 'break_end')),
  -- The moment of the action as measured on the employee's device.
  event_time       timestamptz NOT NULL DEFAULT now(),
  -- Server-received timestamp for audit purposes.
  server_time      timestamptz NOT NULL DEFAULT now(),
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (client_action_id)
);

CREATE INDEX IF NOT EXISTS idx_teal_employee_id    ON public.time_entry_action_log (employee_id);
CREATE INDEX IF NOT EXISTS idx_teal_time_entry_id  ON public.time_entry_action_log (time_entry_id);

COMMENT ON TABLE public.time_entry_action_log IS
  'Append-only log of every clock action. client_action_id is unique so replayed '
  'offline requests are silently de-duplicated. One row per action; one time_entries '
  'row per shift — they are different concerns.';

ALTER TABLE public.time_entry_action_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owners can read their action log" ON public.time_entry_action_log;
CREATE POLICY "Owners can read their action log"
  ON public.time_entry_action_log FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.time_entries te
      WHERE te.id = time_entry_action_log.time_entry_id
        AND te.user_id = auth.uid()
    )
  );
