-- ─────────────────────────────────────────────────────────────────────────────
-- Employee Time Clock Extensions
-- Adds: shift photos, push-token storage, idempotent clock actions,
--       real event timestamps, job-linked shifts, job geofence coords,
--       and an automatic missed-shift cron.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Extend time_entries ────────────────────────────────────────────────────
-- client_action_id: unique ID generated by the mobile app for each action.
--   The backend rejects (or silently ignores) a second request with the same ID.
-- event_time: the actual moment of the action as seen by the employee's device.
--   Replaces always using server now(), which was wrong for offline replay.
-- job_id: links a time-entry to a jobs row (in addition to route_appointments).

-- NOTE: client_action_id was intentionally NOT kept on time_entries.
-- Idempotency is handled by the time_entry_action_log table (see migration
-- 20260702120000_fix_timeclock_cron_and_idempotency.sql). Storing it here
-- would overwrite the id on each action within the same shift row.
ALTER TABLE public.time_entries
  ADD COLUMN IF NOT EXISTS event_time timestamptz,
  ADD COLUMN IF NOT EXISTS job_id     uuid REFERENCES public.jobs(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_time_entries_job_id
  ON public.time_entries (job_id)
  WHERE job_id IS NOT NULL;

COMMENT ON COLUMN public.time_entries.event_time IS
  'The actual moment of the clock action as measured on the employee device. Stored alongside the server-received timestamp.';
COMMENT ON COLUMN public.time_entries.job_id IS
  'Optional reference to jobs.id. Set when the shift is linked to the Jobs feature rather than a route_appointment.';

-- ── 2. Add geofence data to jobs ──────────────────────────────────────────────
-- The employee app validates distance client-side; the backend re-validates using
-- these coordinates so the client cannot spoof its location.

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS site_latitude          numeric(10, 7),
  ADD COLUMN IF NOT EXISTS site_longitude         numeric(10, 7),
  ADD COLUMN IF NOT EXISTS geofence_radius_meters integer NOT NULL DEFAULT 200;

COMMENT ON COLUMN public.jobs.site_latitude IS
  'Latitude of the job site used for server-side geofence validation on clock-in.';
COMMENT ON COLUMN public.jobs.site_longitude IS
  'Longitude of the job site used for server-side geofence validation on clock-in.';
COMMENT ON COLUMN public.jobs.geofence_radius_meters IS
  'Allowed radius (in meters) around site_lat/lng for a valid clock-in. Default 200 m.';

-- ── 3. Shift-photo table ──────────────────────────────────────────────────────
-- Stores metadata for before/after/during photos taken by employees.
-- Actual images live in the 'shift-photos' Storage bucket.

CREATE TABLE IF NOT EXISTS public.time_entry_photos (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  time_entry_id uuid        NOT NULL REFERENCES public.time_entries(id) ON DELETE CASCADE,
  employee_id   uuid        NOT NULL,
  user_id       uuid        NOT NULL,
  photo_type    text        NOT NULL CHECK (photo_type IN ('before', 'after', 'during')),
  storage_path  text        NOT NULL,   -- bucket-relative path
  caption       text,
  taken_at      timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tep_time_entry_id ON public.time_entry_photos (time_entry_id);
CREATE INDEX IF NOT EXISTS idx_tep_employee_id   ON public.time_entry_photos (employee_id);
CREATE INDEX IF NOT EXISTS idx_tep_user_id       ON public.time_entry_photos (user_id);

COMMENT ON TABLE public.time_entry_photos IS
  'Before / after / during photos taken by employees during a Time Clock shift.';
COMMENT ON COLUMN public.time_entry_photos.storage_path IS
  'Path inside the shift-photos Storage bucket: {user_id}/{time_entry_id}/{type}_{uuid}.jpg';

ALTER TABLE public.time_entry_photos ENABLE ROW LEVEL SECURITY;

-- Business owner can view and delete their employees' shift photos.
DROP POLICY IF EXISTS "Owners can read shift photos" ON public.time_entry_photos;
CREATE POLICY "Owners can read shift photos"
  ON public.time_entry_photos FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Owners can delete shift photos" ON public.time_entry_photos;
CREATE POLICY "Owners can delete shift photos"
  ON public.time_entry_photos FOR DELETE
  USING (auth.uid() = user_id);

-- Inserts and updates are done exclusively through edge functions (service role).

-- ── 4. Employee device-token table ───────────────────────────────────────────
-- Stores FCM / APNs push tokens for the employee mobile app.
-- The edge function upserts on (employee_id, token) so re-registrations are safe.

CREATE TABLE IF NOT EXISTS public.employee_device_tokens (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id  uuid        NOT NULL,
  user_id      uuid        NOT NULL,
  token        text        NOT NULL,
  platform     text        NOT NULL CHECK (platform IN ('ios', 'android', 'web')),
  is_active    boolean     NOT NULL DEFAULT true,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, token)
);

CREATE INDEX IF NOT EXISTS idx_edt_employee_id ON public.employee_device_tokens (employee_id);
CREATE INDEX IF NOT EXISTS idx_edt_user_id     ON public.employee_device_tokens (user_id);

COMMENT ON TABLE public.employee_device_tokens IS
  'Push notification tokens (FCM/APNs) for the employee Time Clock mobile app.';

ALTER TABLE public.employee_device_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owners can view employee device tokens" ON public.employee_device_tokens;
CREATE POLICY "Owners can view employee device tokens"
  ON public.employee_device_tokens FOR SELECT
  USING (auth.uid() = user_id);

-- ── 5. Storage bucket for shift photos ───────────────────────────────────────
-- Private bucket (no public URLs). Signed URLs are generated by the edge function.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'shift-photos',
  'shift-photos',
  false,
  10485760,   -- 10 MB per file
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
ON CONFLICT (id) DO NOTHING;

-- Business owner can download photos whose path starts with their user_id.
DROP POLICY IF EXISTS "Owners can read shift photos in storage" ON storage.objects;
CREATE POLICY "Owners can read shift photos in storage"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'shift-photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

-- NOTE: The missed-shift cron is defined in the next migration
-- (20260702120000_fix_timeclock_cron_and_idempotency.sql) using the
-- existing timezone-aware refresh_job_temporal_statuses() function.
